export const GET_TASKS = 'GET_TASK';
export const GET_TASKS_SHEET = 'GET_TASK_SHEET';
export const TOGGLE_COMPLETE_TRUE = 'TOGGLE_COMPLETE_TRUE';
export const TITLE_BAR_TOUCH_TITLE = 'TITLE_BAR_TOUCH_TITLE';