export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';